apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-publisher
  labels:
    app: rabbitmq-publisher
spec:
  selector:
    matchLabels:
      app: rabbitmq-publisher
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq-publisher
    spec:
      containers:
      - name: rabbitmq-publisher
        image: natalicot/rmq-publisher:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: RABBIT_PORT
          value: "5672"
        - name: RABBIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: RABBIT_USERNAME
        - name: RABBIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: RABBIT_PASSWORD
        - name: RABBIT_HOST
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: RABBIT_HOST
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-publisher
spec:
  selector:
    app: rabbitmq-publisher
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80