apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
type: Opaque
data:
  RABBIT_USERNAME: Z3Vlc3Q= 
  RABBIT_PASSWORD: Z3Vlc3Q=
  RABBIT_HOST: ZWMyLTE4LTE1OS0xMjktMTgyLmV1LWNlbnRyYWwtMS5jb21wdXRlLmFtYXpvbmF3cy5jb20=
  RABBIT_CONECTION_STRING: YW1xcDovL2d1ZXN0Omd1ZXN0QGVjMi0xOC0xNTktMTI5LTE4Mi5ldS1jZW50cmFsLTEuY29tcHV0ZS5hbWF6b25hd3MuY29tOjU2NzIv # base64 encoded value of format amqp://guest:password@localhost:5672/vhost